### ISSUE TITLE
Versioning for Python wrappers

### ISSUE THREAD

**Issue by marktsuchida** [flimlib/flimlib#68]
I'm getting ready to set up publishing to PyPI and wondering what to do about version numbering.
I think there are a few options:

- Use a single version for C, Java, and Python
    - This could result in releases that don't change anything for Java while Python wrappers are added
    - Which violates SemVer, e.g., if only the Python wrappers have a backward-incompatible change
- Use separate tag prefixes (`flimlib-2.1.2` for C and Java; `python-0.1.0` for Python)
- Separate out the Python wrappers into a separate repo (`flimlib-python`) with its own versioning
    - The `flimlib` C sources will then be a build-time dependency of `flimlib-python`

I'm leaning toward the last option, which seems cleanest.
(In that case the Java wrappers could also be a separate repo from the C library, but I'm not proposing that at the moment.)

@ctrueden Do you have any opinions?

Cc: @facetorched

**Comment by ctrueden** [comment]
I like the first option. For SemVer, you can bump the major version any time there is a backwards-incompatible change in any API of any language; it's not a violation per se. (It's the other way—doing a minor or patch bump but breaking API compatibility—that would violate SemVer.)

I'm not staunchly opposed to the separate repository approach, but it is making more work for yourself, which is IMHO unnecessary, and complicating the infrastructure. For what benefit? Just so that we make fewer Java releases? It's not a big deal, and having the aligned versioning here keeps things simpler for consumers, so they can easily see which artifacts go together across languages.

**Comment by marktsuchida** [comment]
Thanks, that does seem like a fair point for this project.

Am I guessing right that the current release procedure is to run `mvn release:prepare`, and let the CI do the rest?

In that case I'll change `setup.py` to get the version number by parsing `pom.xml`, and the `build-python` workflow to automatically build, and upload to PyPI (when building a `flimlib-*` tag). (The Python build is completely orthogonal to Maven/CMake.)

**Comment by marktsuchida** [comment]
@ctrueden I think the Python side is ready for a new release (except for a few updates to README, etc.), which I'd like to do soon if there's no objection, since @facetorched's project needs flimlib as a dependency.

Are the Java CI scripts still expected to be functional for releasing, and is running `mvn release:prepare` the right method?

And since I'm asking about this (and I'm not deeply familiar with the SciJava CI and release practices), what is the future plan (if any) for the (Java) CI? Is AppVeyor going to be retired now that GH Actions can run Windows? Is there a SciJava project that already does such things that should be imitated by flimlib? Or is everything up to date for the current way of doing things? Or does a new way need to be devised? No pressure here, I just want to understand the situation/thinking, since the shell scripts (and PowerShell scripts) are pretty opaque to me (would take some time to study).

**Comment by ctrueden** [comment]
@marktsuchida Sorry for the delay in reply. For Java projects we use a script `release-version.sh` which uses `mvn release:prepare` under the hood. On the GitHub Actions side, the `.github/build.sh` calls a script `ci-build.sh` which invokes `mvn release:perform` when a telltale file `release.properties` is present on an appropriately named tag.

Both of these scripts are here: https://github.com/scijava/scijava-scripts

And the release process for SciJava software is documented at: https://imagej.net/develop/releasing

For flimlib specifically: the situation is less clean, due to the multi-platform binary build requirement. I'll try to answer your specific questions:

> what is the future plan (if any) for the (Java) CI? Is AppVeyor going to be retired now that GH Actions can run Windows?

Yes, I would like to stop using AppVeyor. Nice for GitHub Actions to do everything, since it has all the platforms.

> Is there a SciJava project that already does such things that should be imitated by flimlib?

Unfortunately, I don't think so. The other SciJava project need builds for multiple platforms is [imagej-launcher](https://github.com/imagej/imagej-launcher), and it also hasn't been fixed up yet (https://github.com/imagej/imagej-launcher/issues/86).

> Or is everything up to date for the current way of doing things? Or does a new way need to be devised?

Some of each, I think. The exists-maven-plugin helps with multi-platform deployment, in that it will only deploy a particular release artifact if that version has not already been deployed. Without this plugin, two platforms building the same release version of something will clash when each tries to deploy the POM and plain JAR artifacts, and one of them wins.

So my hope is that making multi-platform deployment work will be as simple as each platform independently picking up on the release tag, and independently doing `release:perform`, same as usual, but with redundant artifacts only deployed once by the first platform to finish its build. IIRC, this is how it was previously working with AppVeyor+Travis CI.

I'd be happy to have a pair session with you to iron out this stuff, if needed. Or if you like, you could just go ahead and give a try to ditching the AppVeyor config here in flimlib in favor of a unified GHA build matrix. Let me know how I can help.

**Comment by marktsuchida** [comment]
@ctrueden Thanks!

> it will only deploy a particular release artifact if that version has not already been deployed

This behavior is needed for PyPI, too (deploying the same filename the second time is an error). If everything is on GH Actions, it can be done by aggregating the artifacts and then uploading them all together in one job, as I've done for the [Python CI](https://github.com/flimlib/flimlib/blob/7650b2eaa64e975d1e868c2bd6f74848520ea902/.github/workflows/build-python.yml#L42). Do you think this approach is possible with Maven? Naively I think we just need a way to tell `ci-build.sh` not to perform the actual deployment, plus a separate script to do only the deployment given a collection of artifacts.

> I'd be happy to have a pair session with you to iron out this stuff, if needed.

That would be great. Maybe I can release once as is, to remove all time pressure, and we can schedule a time?

**Comment by ctrueden** [comment]
> it can be done by aggregating the artifacts and then uploading them all together in one job, as I've done for the [Python CI](https://github.com/flimlib/flimlib/blob/7650b2eaa64e975d1e868c2bd6f74848520ea902/.github/workflows/build-python.yml#L42). Do you think this approach is possible with Maven?

That is how we used to do it when we had our own Jenkins. IIRC, a Jenkins job can have sub-jobs, which the main job can wait till they complete, and then grab the desired files out of those sub-job builds, copying them all into `/target` and then there was a Groovy script written by Johannes that Jenkins would run to attach them all as classifier artifacts to the build and deploy them. Johannes wrote up the scheme somewhere, but I couldn't find the write-up in a quick search just now; I could probably dig up the old Jenkins job from our archive, and/or look harder for the old content describing it, if we decide to go that route and need hints on how to proceed.

> we can schedule a time?

Sure, it's still on my radar to update this repo, as well as imagej-launcher, to ditch AppVeyor in favor of GHA. But as always, there's a lot of competing priorities. I'm commenting on this issue today mostly to bump it's "last updated" datestamp, which will push it further up the support queue mechanism I'm developing, which weighs items by recency... :smile:
